package api

import (
	"log/slog"
	"net/http"
	"time"

	"onion-spider/internal/logging"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

// SafeLogger logs every request as a single structured slog record without
// client IPs, raw paths, or query strings. Search terms, reset/verification
// tokens and onion URLs are sensitive product data, not request telemetry.
// MetricsMiddleware already records the route, status and duration as bounded
// Prometheus labels, so retaining another copy of those secrets has no upside.
//
// The request ID generated by chi's middleware.RequestID is propagated into
// the request context under our own key so handler-level logs can pick it up
// automatically through the contextHandler in internal/logging.
func SafeLogger() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)

			// Propagate the chi request ID into our logging context.
			reqID := middleware.GetReqID(r.Context())
			ctx := logging.WithRequestID(r.Context(), reqID)
			r = r.WithContext(ctx)

			defer func() {
				route := chi.RouteContext(r.Context()).RoutePattern()
				if route == "" {
					route = "unmatched"
				}
				slog.LogAttrs(ctx, slog.LevelInfo, "http_request",
					slog.String("method", r.Method),
					slog.String("route", route),
					slog.Int("status", ww.Status()),
					slog.Int("bytes", ww.BytesWritten()),
					slog.Duration("dur", time.Since(start)),
				)
			}()
			next.ServeHTTP(ww, r)
		})
	}
}
