package api

import (
	"log/slog"
	"net/http"
	"time"

	"onion-spider/internal/logging"

	"github.com/go-chi/chi/v5/middleware"
)

// SafeLogger logs every request as a single structured slog record. The query
// string is REDACTED for sensitive paths (e.g. /api/auth/verify which carries
// the verification token — that token would otherwise end up in syslog).
//
// The request ID generated by chi's middleware.RequestID is propagated into
// the request context under our own key so handler-level logs can pick it up
// automatically through the contextHandler in internal/logging.
func SafeLogger(sensitivePaths ...string) func(http.Handler) http.Handler {
	sensitive := make(map[string]struct{}, len(sensitivePaths))
	for _, p := range sensitivePaths {
		sensitive[p] = struct{}{}
	}
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)

			// Propagate the chi request ID into our logging context.
			reqID := middleware.GetReqID(r.Context())
			ctx := logging.WithRequestID(r.Context(), reqID)
			r = r.WithContext(ctx)

			defer func() {
				path := r.URL.Path
				query := r.URL.RawQuery
				if _, isSensitive := sensitive[path]; isSensitive && query != "" {
					query = "[REDACTED]"
				}
				slog.LogAttrs(ctx, slog.LevelInfo, "http_request",
					slog.String("method", r.Method),
					slog.String("path", path),
					slog.String("query", query),
					slog.Int("status", ww.Status()),
					slog.Int("bytes", ww.BytesWritten()),
					slog.Duration("dur", time.Since(start)),
					slog.String("ip", ClientIP(r)),
				)
			}()
			next.ServeHTTP(ww, r)
		})
	}
}
